/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.TALKDAO.TalkDAO;

/**
 *
 * @author ht3000052
 */
public class Conversation extends javax.swing.JPanel {
    private int id,indice;
    Talks talksScreen;
    /**
     * Creates new form Conversation
     */
    public Conversation() {
        initComponents();
    }
    
    public Conversation(Talks t)
    {
        initComponents();
        this.talksScreen = t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        btnAddPhrase = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnListen = new javax.swing.JButton();

        setBackground(new java.awt.Color(206, 214, 224));
        setMinimumSize(new java.awt.Dimension(446, 26));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionado(evt);
            }
        });

        Name.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Name.setText("Nome");

        btnAddPhrase.setText("Add");
        btnAddPhrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhraseActionPerformed(evt);
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnListen.setText("Listen");
        btnListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnListen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAddPhrase)
                .addComponent(deleteButton)
                .addComponent(Name)
                .addComponent(btnEdit)
                .addComponent(btnListen))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        talksScreen.removeElement(this);
        TalkDAO talk = new TalkDAO();
        talk.deleteTalk(this.id);
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void btnAddPhraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhraseActionPerformed
        // TODO add your handling code here:
        talksScreen.setVisible(false);
        Phrases phraseFrame = new Phrases(talksScreen,this.id);
        phraseFrame.setTalkName(this.Name.getText());
        phraseFrame.setVisible(true);
        
    }//GEN-LAST:event_btnAddPhraseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        TalkEditModal talkModal = new TalkEditModal(this.talksScreen);
        talkModal.setTalkId(this.id);
        talkModal.setTalkName(this.Name.getText());
        talkModal.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void selecionado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionado
        // TODO add your handling code here:
        talksScreen.setVisible(false);
        Phrases phraseFrame = new Phrases(talksScreen,this.id);
        phraseFrame.setTalkName(this.Name.getText());
        phraseFrame.setVisible(true);
    }//GEN-LAST:event_selecionado

    private void btnListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListenActionPerformed
        // TODO add your handling code here:
        ListenScreen listenScreen = new ListenScreen(talksScreen,this.id);
        listenScreen.setVisible(true);
        listenScreen.setName(this.Name.getText());
        talksScreen.setVisible(false);
    }//GEN-LAST:event_btnListenActionPerformed
    
    public void setName(String name)
    {
        if(name == null)
             name = "";
        this.Name.setText(name);
    }
    
    public void setId(int id)
    {
        this.id = id;
    }
    
    public void setIndice(int indice)
    {
        this.indice = indice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JButton btnAddPhrase;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnListen;
    private javax.swing.JButton deleteButton;
    // End of variables declaration//GEN-END:variables
}
