/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.TALKDAO.TalkDAO;

/**
 *
 * @author ht3000052
 */
public class Conversation extends javax.swing.JPanel {
    private int id,indice;
    Talks talksScreen;
    /**
     * Creates new form Conversation
     */
    public Conversation() {
        initComponents();
    }
    
    public Conversation(Talks t)
    {
        initComponents();
        this.talksScreen = t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        iconListen = new javax.swing.JLabel();
        iconNewPhrase = new javax.swing.JLabel();
        iconEdit = new javax.swing.JLabel();
        iconDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(206, 214, 224));
        setMinimumSize(new java.awt.Dimension(446, 26));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionado(evt);
            }
        });

        Name.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Name.setText("Nome");

        iconListen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ear.png"))); // NOI18N
        iconListen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconListen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconListenMouseClicked(evt);
            }
        });

        iconNewPhrase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/new.png"))); // NOI18N
        iconNewPhrase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconNewPhrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconNewPhraseMouseClicked(evt);
            }
        });

        iconEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/tools.png"))); // NOI18N
        iconEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEditMouseClicked(evt);
            }
        });

        iconDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/remove.png"))); // NOI18N
        iconDelete.setToolTipText("");
        iconDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(iconListen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconNewPhrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconDelete)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconListen)
            .addComponent(iconNewPhrase)
            .addComponent(iconEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(iconDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Name)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionado
        // TODO add your handling code here:
        talksScreen.setVisible(false);
        Phrases phraseFrame = new Phrases(talksScreen,this.id);
        phraseFrame.setTalkName(this.Name.getText());
        phraseFrame.setVisible(true);
    }//GEN-LAST:event_selecionado

    private void iconListenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconListenMouseClicked
        // TODO add your handling code here:
        ListenScreen listenScreen = new ListenScreen(talksScreen,this.id);
        listenScreen.setVisible(true);
        listenScreen.setName(this.Name.getText());
        talksScreen.setVisible(false);
    }//GEN-LAST:event_iconListenMouseClicked

    private void iconNewPhraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconNewPhraseMouseClicked
        // TODO add your handling code here:
         talksScreen.setVisible(false);
        Phrases phraseFrame = new Phrases(talksScreen,this.id);
        phraseFrame.setTalkName(this.Name.getText());
        phraseFrame.setVisible(true);
    }//GEN-LAST:event_iconNewPhraseMouseClicked

    private void iconEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEditMouseClicked
        // TODO add your handling code here:
        TalkEditModal talkModal = new TalkEditModal(this.talksScreen);
        talkModal.setTalkId(this.id);
        talkModal.setTalkName(this.Name.getText());
        talkModal.setVisible(true);
    }//GEN-LAST:event_iconEditMouseClicked

    private void iconDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconDeleteMouseClicked
        // TODO add your handling code here:
        talksScreen.removeElement(this);
        TalkDAO talk = new TalkDAO();
        talk.deleteTalk(this.id);
    }//GEN-LAST:event_iconDeleteMouseClicked
    
    public void setName(String name)
    {
        if(name == null)
             name = "";
        this.Name.setText(name);
    }
    
    public void setId(int id)
    {
        this.id = id;
    }
    
    public void setIndice(int indice)
    {
        this.indice = indice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel iconDelete;
    private javax.swing.JLabel iconEdit;
    private javax.swing.JLabel iconListen;
    private javax.swing.JLabel iconNewPhrase;
    // End of variables declaration//GEN-END:variables
}
