/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.PHRASEDAO.Phrase;
import MODEL.PHRASEDAO.PhraseDAO;
import Services.Speaker;
import javax.swing.JLabel;

/**
 *
 * @author David
 */
public class ListenScreen extends javax.swing.JFrame {
    private int talkId;
    Talks talkScreen;
    /**
     * Creates new form ListenScreen
     */
    public ListenScreen() {
        initComponents();
    }    

    ListenScreen(Talks talksScreen, int id) {
        initComponents();
        talkScreen = talksScreen;
        talkId     = id;
        updatePhrases(talkId);
    }
    
    public void setName(String Name) {
        this.Name.setText(Name);
    }
    
    public void updatePhrases(int id)
    {            
      PhraseDAO phrase  = new PhraseDAO();
      Phrase[]  phrases = phrase.getPhrases(id);
      cleanPhrases();
            
      for(int i = 0; i < phrases.length; i++)
      {
          PhraseSpeakerComponent phraseSpeaker = new PhraseSpeakerComponent();
          phraseSpeaker.setPhrase(phrases[i].getPhrase());
          phraseSpeaker.setTranslation(phrases[i].getTranslation());
                    
          this.phrasesPanel.add(phraseSpeaker);
      }           
      
      this.phrasesPanel.updateUI();
      
    }
    
    private void cleanPhrases()
    {
        this.phrasesPanel.removeAll();        
        this.phrasesPanel.repaint();
        this.phrasesPanel.validate();
        this.phrasesPanel.updateUI();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        phrasesPanel = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        iconBack = new javax.swing.JLabel();
        iconListenAll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 214, 224));

        jScrollPane1.setBackground(new java.awt.Color(206, 214, 224));
        jScrollPane1.setBorder(null);

        phrasesPanel.setBackground(new java.awt.Color(206, 214, 224));
        phrasesPanel.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(phrasesPanel);

        Name.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("text");

        iconBack.setIcon(new javax.swing.ImageIcon("E:\\myTalks\\images\\back (1).png")); // NOI18N
        iconBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBackMouseClicked(evt);
            }
        });

        iconListenAll.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        iconListenAll.setIcon(new javax.swing.ImageIcon("E:\\myTalks\\images\\megaphone.png")); // NOI18N
        iconListenAll.setText("LISTEN ALL");
        iconListenAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconListenAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconListenAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(iconBack)
                        .addGap(84, 84, 84)
                        .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(81, 81, 81)
                        .addComponent(iconListenAll)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconListenAll))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconBack)
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconListenAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconListenAllMouseClicked
        // TODO add your handling code here:
        PhraseDAO phrase  = new PhraseDAO();
        Phrase[]  phrases = phrase.getPhrases(this.talkId);
        String   phraseAll = "";
        
        for (int i = 0; i < phrases.length; i++) {
            phraseAll = phraseAll + "   " +phrases[i].getPhrase();
        }
        
        Speaker.speak(phraseAll);
    }//GEN-LAST:event_iconListenAllMouseClicked

    private void iconBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBackMouseClicked
        this.talkScreen.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_iconBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListenScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel iconBack;
    private javax.swing.JLabel iconListenAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel phrasesPanel;
    // End of variables declaration//GEN-END:variables
}
