/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.PHRASEDAO.Phrase;
import MODEL.PHRASEDAO.PhraseDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Phrases extends javax.swing.JFrame {
    private Talks talkScreen;
    private int talkID;
    private List <PhraseComponent> phrasesComponent;
    /**
     * Creates new form Phrases
     */
    public Phrases() {
        initComponents();        
    }
    
    public Phrases(Talks talk, int id)
    {
        initComponents();
        phrasesComponent = new ArrayList<>();
        talkScreen       = talk;
        this.talkID      = id;
                        
        updatePhrases(this.talkID);
    }
    
    public void setTalkName(String name)
    {
        this.talkName.setText(name);
    }
    
    public void setTalkId(int id)
    {
        this.talkID = id;
    }
    
    
    public void removeElement(PhraseComponent phraseComponent)
    {
        this.phrasesPanel.remove(phraseComponent);
        this.phrasesComponent.remove(phraseComponent);
        phrasesPanel.updateUI();
    }
    
    public void updatePhrases(int id)
    {            
      PhraseDAO phrase  = new PhraseDAO();
      Phrase[]  phrases = phrase.getPhrases(id);
      cleanPhrases();
            
      for(int i = 0; i < phrases.length; i++)
      {
          PhraseComponent tempPhrase = new PhraseComponent(this);          
          tempPhrase.setPhraseText(phrases[i].getPhrase());
          tempPhrase.setTranslationText(phrases[i].getTranslation());          
          tempPhrase.setPhraseID(phrases[i].getId());
          tempPhrase.setTalkID(talkID);
          
          this.phrasesComponent.add(tempPhrase);
          this.phrasesPanel.add(tempPhrase);
      }           
      
      this.phrasesPanel.updateUI();
      
    }
    
    private void cleanPhrases()
    {
        this.phrasesPanel.removeAll();
        this.phrasesComponent.removeAll(phrasesComponent);
        this.phrasesPanel.repaint();
        this.phrasesPanel.validate();
        this.phrasesPanel.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        phrasesPanel = new javax.swing.JPanel();
        talkName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNewPhrase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phrasesPanel.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(phrasesPanel);

        talkName.setText("NAME Talk");
        talkName.setToolTipText("Nome da conversa");

        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNewPhrase.setText("NEW");
        btnNewPhrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPhraseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(talkName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewPhrase)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talkName)
                    .addComponent(btnBack)
                    .addComponent(btnNewPhrase))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        talkScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewPhraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPhraseActionPerformed
        // TODO add your handling code here:
        PhraseModal phraseModal = new PhraseModal(this);
        phraseModal.setTalkID(talkID);
        phraseModal.setVisible(true);
        phraseModal.setPhraseId(0);
        
    }//GEN-LAST:event_btnNewPhraseActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phrases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewPhrase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel phrasesPanel;
    private javax.swing.JLabel talkName;
    // End of variables declaration//GEN-END:variables
}
